export const SOUND_PATHS = {
	BATTLELEVEL_MP3: "./Assets/Sounds/battlelevel_mp3.mp3",
	BATTLELEVEL_OGG: "./Assets/Sounds/battlelevel_ogg.ogg",
	BUTTONBATTLE_MP3: "./Assets/Sounds/buttonbattle_mp3.mp3",
	BUTTONBATTLE_OGG: "./Assets/Sounds/buttonbattle_ogg.ogg",
	BUTTONCRAFTING_MP3: "./Assets/Sounds/buttoncrafting_mp3.mp3",
	BUTTONCRAFTING_OGG: "./Assets/Sounds/buttoncrafting_ogg.ogg",
	BUTTON_MP3: "./Assets/Sounds/button_mp3.mp3",
	BUTTON_OGG: "./Assets/Sounds/button_ogg.ogg",
	CARDSWIPE_MP3: "./Assets/Sounds/cardswipe_mp3.mp3",
	CARDSWIPE_OGG: "./Assets/Sounds/cardswipe_ogg.ogg",
	CRAFTINGLEVEL_MP3: "./Assets/Sounds/craftinglevel_mp3.mp3",
	CRAFTINGLEVEL_OGG: "./Assets/Sounds/craftinglevel_ogg.ogg",
	DESTROYOBJECT_MP3: "./Assets/Sounds/destroyObject_mp3.mp3",
	DESTROYOBJECT_OGG: "./Assets/Sounds/destroyObject_ogg.ogg",
	ITEMERROR_MP3: "./Assets/Sounds/itemerror_mp3.mp3",
	ITEMERROR_OGG: "./Assets/Sounds/itemerror_ogg.ogg",
	MAINMENU_MP3: "./Assets/Sounds/mainmenu_mp3.mp3",
	MAINMENU_OGG: "./Assets/Sounds/mainmenu_ogg.ogg",
	NEWITEMCRAFTED_MP3: "./Assets/Sounds/newitemcrafted_mp3.mp3",
	NEWITEMCRAFTED_OGG: "./Assets/Sounds/newitemcrafted_ogg.ogg",
	OUTPOST_MP3: "./Assets/Sounds/outpost_mp3.mp3",
	OUTPOST_OGG: "./Assets/Sounds/outpost_ogg.ogg",
	PLACEOBJECT_MP3: "./Assets/Sounds/placeObject_mp3.mp3",
	PLACEOBJECT_OGG: "./Assets/Sounds/placeObject_ogg.ogg",
	ROCKSLING_MP3: "./Assets/Sounds/rocksling_mp3.mp3",
	ROCKSLING_OGG: "./Assets/Sounds/rocksling_ogg.ogg",
	ROPEDART_MP3: "./Assets/Sounds/ropedart_mp3.mp3",
	ROPEDART_OGG: "./Assets/Sounds/ropedart_ogg.ogg",
	SANDPAPERWALL_MP3: "./Assets/Sounds/sandpaperwall_mp3.mp3",
	SANDPAPERWALL_OGG: "./Assets/Sounds/sandpaperwall_ogg.ogg",
	SPIKEOUTPOST_MP3: "./Assets/Sounds/spikeoutpost_mp3.mp3",
	SPIKEOUTPOST_OGG: "./Assets/Sounds/spikeoutpost_ogg.ogg",
	SPIKEWALL_MP3: "./Assets/Sounds/spikewall_mp3.mp3",
	SPIKEWALL_OGG: "./Assets/Sounds/spikewall_ogg.ogg",
	SPIKE_MP3: "./Assets/Sounds/spike_mp3.mp3",
	SPIKE_OGG: "./Assets/Sounds/spike_ogg.ogg",
	SWORD_MP3: "./Assets/Sounds/sword_mp3.mp3",
	SWORD_OGG: "./Assets/Sounds/sword_ogg.ogg",
	WALL_MP3: "./Assets/Sounds/wall_mp3.mp3",
	WALL_OGG: "./Assets/Sounds/wall_ogg.ogg",
};
export enum SOUNDS {
	BATTLELEVEL = "battlelevel",
	BUTTON = "button",
	BUTTONCRAFTING = "buttoncrafting",
	BUTTONBATTLE = "buttonbattle",
	CARDSWIPE = "cardswipe",
	CRAFTINGLEVEL = "craftinglevel",
	DESTROYOBJECT = "destroyobject",
	ITEMERROR = "itemerror",
	MAINMENU = "mainmenu",
	NEWITEMCRAFTED = "newitemcrafted",
	//OUTPOST = "outpost",
	PLACEOBJECT = "placeobject",
	/*
	ROCKSLING = "rocksling",
	ROPEDART = "ropedart",
	SANDPAPERWALL = "sandpaperwall",
	SPIKEOUTPOST = "spikeoutpost",
	SPIKEWALL = "spikewall",
	*/
	SPIKE = "spike",
	SWORD = "sword",
	WALL = "wall",
}
